# -*- coding: utf-8 -*-
"""
Module: pigit/termui/_syntax_configs.py
Description: Language syntax keyword configurations for the tokenizer.
Author: Zev
Date: 2026-04-28
"""

from __future__ import annotations

from . import palette

# ── Language configurations ──
_LANGUAGE_CONFIGS: dict[str, dict] = {
    # ── Python ──
    "py": {
        "keyword_categories": {
            "control": {
                "if",
                "elif",
                "else",
                "for",
                "while",
                "return",
                "break",
                "continue",
                "yield",
                "raise",
                "try",
                "except",
                "finally",
                "with",
                "async",
                "await",
                "pass",
            },
            "decl": {
                "def",
                "class",
                "import",
                "from",
                "as",
                "global",
                "nonlocal",
                "lambda",
                "assert",
                "del",
            },
            "storage": set(),
            "type": {
                "int",
                "str",
                "float",
                "bool",
                "list",
                "dict",
                "tuple",
                "set",
                "frozenset",
                "bytes",
                "bytearray",
                "memoryview",
                "object",
                "type",
                "None",
                "True",
                "False",
                "Ellipsis",
                "NotImplemented",
            },
            "operator": {"and", "or", "not", "in", "is"},
        },
        "builtins": {
            "abs",
            "all",
            "any",
            "ascii",
            "bin",
            "bool",
            "breakpoint",
            "bytearray",
            "bytes",
            "callable",
            "chr",
            "classmethod",
            "compile",
            "complex",
            "delattr",
            "dict",
            "dir",
            "divmod",
            "enumerate",
            "eval",
            "exec",
            "filter",
            "float",
            "format",
            "frozenset",
            "getattr",
            "globals",
            "hasattr",
            "hash",
            "help",
            "hex",
            "id",
            "input",
            "int",
            "isinstance",
            "issubclass",
            "iter",
            "len",
            "list",
            "locals",
            "map",
            "max",
            "memoryview",
            "min",
            "next",
            "object",
            "oct",
            "open",
            "ord",
            "pow",
            "print",
            "property",
            "range",
            "repr",
            "reversed",
            "round",
            "set",
            "setattr",
            "slice",
            "sorted",
            "staticmethod",
            "str",
            "sum",
            "super",
            "tuple",
            "type",
            "vars",
            "zip",
            "__import__",
        },
        "comment": "#",
        "strings": {'"', "'"},
    },
    # ── JavaScript / TypeScript ──
    "js": {
        "keyword_categories": {
            "control": {
                "if",
                "else",
                "for",
                "while",
                "return",
                "break",
                "continue",
                "switch",
                "case",
                "default",
                "try",
                "catch",
                "finally",
                "throw",
                "yield",
                "await",
                "async",
                "do",
                "debugger",
            },
            "decl": {
                "function",
                "const",
                "let",
                "var",
                "class",
                "extends",
                "import",
                "from",
                "export",
                "default",
                "static",
                "get",
                "set",
                "of",
                "new",
                "this",
                "super",
                "with",
                "delete",
                "void",
                "typeof",
                "instanceof",
            },
            "storage": set(),
            "type": {
                "null",
                "undefined",
                "NaN",
                "Infinity",
                "true",
                "false",
            },
            "operator": {"in", "of", "as"},
        },
        "builtins": {
            "Array",
            "Boolean",
            "Date",
            "Error",
            "Function",
            "JSON",
            "Math",
            "Number",
            "Object",
            "Promise",
            "RegExp",
            "String",
            "Symbol",
            "console",
            "document",
            "window",
            "parseInt",
            "parseFloat",
            "isNaN",
            "isFinite",
            "decodeURI",
            "decodeURIComponent",
            "encodeURI",
            "encodeURIComponent",
        },
        "comment": "//",
        "block_comment": ("/*", "*/"),
        "strings": {'"', "'", "`"},
    },
    "ts": {"_alias": "js"},
    "jsx": {"_alias": "js"},
    "tsx": {"_alias": "js"},
    # ── Go ──
    "go": {
        "keyword_categories": {
            "control": {
                "if",
                "else",
                "for",
                "range",
                "return",
                "break",
                "continue",
                "switch",
                "case",
                "default",
                "fallthrough",
                "goto",
            },
            "decl": {
                "func",
                "package",
                "import",
                "const",
                "var",
                "type",
                "struct",
                "interface",
                "map",
                "chan",
                "select",
                "go",
                "defer",
            },
            "storage": set(),
            "type": {
                "int",
                "int8",
                "int16",
                "int32",
                "int64",
                "uint",
                "uint8",
                "uint16",
                "uint32",
                "uint64",
                "uintptr",
                "float32",
                "float64",
                "complex64",
                "complex128",
                "bool",
                "byte",
                "rune",
                "string",
                "error",
                "nil",
                "true",
                "false",
            },
            "operator": set(),
        },
        "builtins": {
            "append",
            "cap",
            "close",
            "complex",
            "copy",
            "delete",
            "imag",
            "len",
            "make",
            "new",
            "panic",
            "print",
            "println",
            "real",
            "recover",
        },
        "comment": "//",
        "block_comment": ("/*", "*/"),
        "strings": {'"', "`"},
    },
    # ── Rust ──
    "rs": {
        "keyword_categories": {
            "control": {
                "if",
                "else",
                "match",
                "for",
                "while",
                "loop",
                "return",
                "break",
                "continue",
                "await",
                "async",
            },
            "decl": {
                "fn",
                "pub",
                "use",
                "mod",
                "struct",
                "enum",
                "trait",
                "impl",
                "type",
                "crate",
                "extern",
                "dyn",
                "where",
                "let",
            },
            "storage": {"const", "static", "mut", "ref", "move", "unsafe"},
            "type": {"Self", "self", "true", "false"},
            "operator": {"as", "in", "where"},
        },
        "color_overrides": {
            "keyword_storage": palette.RED,
        },
        "special_patterns": [(r"'[a-zA-Z_]\w*", "special")],
        "comment": "//",
        "block_comment": ("/*", "*/"),
        "strings": {'"'},
    },
    # ── Java ──
    "java": {
        "keyword_categories": {
            "control": {
                "if",
                "else",
                "for",
                "while",
                "return",
                "break",
                "continue",
                "switch",
                "case",
                "default",
                "try",
                "catch",
                "finally",
                "throw",
                "do",
                "goto",
            },
            "decl": {
                "class",
                "interface",
                "enum",
                "extends",
                "implements",
                "import",
                "package",
                "new",
                "this",
                "super",
                "abstract",
                "native",
                "strictfp",
                "synchronized",
                "transient",
                "volatile",
                "throws",
                "instanceof",
            },
            "storage": {
                "public",
                "private",
                "protected",
                "static",
                "final",
                "const",
            },
            "type": {
                "boolean",
                "byte",
                "char",
                "short",
                "int",
                "long",
                "float",
                "double",
                "void",
                "null",
                "true",
                "false",
            },
            "operator": set(),
        },
        "builtins": {
            "String",
            "Object",
            "Integer",
            "Boolean",
            "Double",
            "Float",
            "Long",
            "Short",
            "Byte",
            "Character",
            "System",
            "Math",
            "Thread",
            "Exception",
            "Runtime",
            "Class",
        },
        "comment": "//",
        "block_comment": ("/*", "*/"),
        "strings": {'"'},
    },
    "kt": {"_alias": "java"},
    # ── C / C++ ──
    "c": {
        "keyword_categories": {
            "control": {
                "if",
                "else",
                "for",
                "while",
                "return",
                "break",
                "continue",
                "switch",
                "case",
                "default",
                "do",
                "goto",
            },
            "decl": {
                "struct",
                "enum",
                "union",
                "typedef",
                "extern",
                "inline",
                "sizeof",
            },
            "storage": {
                "auto",
                "const",
                "register",
                "restrict",
                "static",
                "volatile",
                "signed",
                "unsigned",
            },
            "type": {
                "char",
                "short",
                "int",
                "long",
                "float",
                "double",
                "void",
                "bool",
                "true",
                "false",
                "NULL",
                "nullptr",
            },
            "operator": set(),
        },
        "preprocessor": True,
        "comment": "//",
        "block_comment": ("/*", "*/"),
        "strings": {'"', "'"},
    },
    "cpp": {"_alias": "c"},
    "h": {"_alias": "c"},
    "hpp": {"_alias": "c"},
    # ── Shell ──
    "sh": {
        "keyword_categories": {
            "control": {
                "if",
                "then",
                "else",
                "elif",
                "fi",
                "for",
                "while",
                "do",
                "done",
                "case",
                "esac",
                "return",
                "select",
                "until",
                "in",
            },
            "decl": {
                "function",
                "export",
                "source",
                "local",
                "alias",
                "trap",
                "eval",
                "exec",
                "exit",
                "shift",
                "unset",
            },
            "storage": set(),
            "type": set(),
            "operator": set(),
        },
        "comment": "#",
        "strings": {'"', "'"},
        "variables": True,
    },
    "bash": {"_alias": "sh"},
    "zsh": {"_alias": "sh"},
    # ── Markdown ──
    "md": {
        "keyword_categories": {},
        "markdown_rules": True,
    },
    # ── YAML ──
    "yaml": {
        "keyword_categories": {},
        "comment": "#",
        "strings": {'"', "'"},
    },
    "yml": {"_alias": "yaml"},
    # ── TOML ──
    "toml": {
        "keyword_categories": {},
        "comment": "#",
        "strings": {'"'},
    },
    # ── INI ──
    "ini": {
        "keyword_categories": {},
        "comment": ";",
        "strings": set(),
    },
    # ── HTML / XML ──
    "html": {
        "keyword_categories": {},
        "comment": None,
        "strings": {'"', "'"},
        "tag_highlight": True,
    },
    "xml": {"_alias": "html"},
    # ── CSS ──
    "css": {
        "keyword_categories": {},
        "block_comment": ("/*", "*/"),
        "strings": {'"', "'"},
    },
    "scss": {"_alias": "css"},
    "less": {"_alias": "css"},
    # ── Generic fallback ──
    "generic": {
        "keyword_categories": {},
        "comment": "#",
        "strings": {'"', "'"},
    },
}
