#!/usr/env bash

_pigit_completion(){
  if [[ "${COMP_CWORD}" == "1" ]];then
      COMP_WORD="cm m SD wx cR pull cmd --show-commands fr iR iX cF Cl ue --show-part-command bs --complete sd ll bm lc b --simple ls mv --help tx savepd Sd --config --commit RS cf ix ma --since bS mt ld cA push Ru Su pp -t --print mF -f Ra open Si --create-config sl t -r --issue user CT lr wC wr --shell fetch repo email f s p sD --report ws --path lv pt pA add R Co Ca Rl cO iu report mC iD -h fc co bd cd ia wR Rm --util wS bM --version -s fm l1 mS pa rm fu rename CO clear pc -c --count -i bc -p bL -v fb wM Rs --information cr sp Sc --create-ignore l id --reverse Ce fC Ct wD wc --types c --author cs wm iA ta wX ca Rp bl Rx pF --dry-run wd ir pf"
      COMPREPLY=($(compgen -W "$COMP_WORD" -- ${COMP_WORDS[${COMP_CWORD}]}))
  fi
}

complete -F _pigit_completion pigit
