#!/usr/env bash

_pigit_completion(){
  if [[ "${COMP_CWORD}" == "1" ]];then
      COMP_WORD="co sD cmd --shell fc pa -c --author --print email lc CO CT id p cf RS -h mt wM --util fr bc bs wc -v pf Ru s open wd ll bl cs --simple bM Rs cF iA add cO cR pull wD iR ws wm --path pA m --commit cr --config fC bd l R ld bS --types cA fetch cm --create-config report Rp pp ma wr fm -i -p iD pt --issue wx --complete --show-commands --create-ignore -s Si ca sd iX -f Rl --show-part-command --reverse tx Sd Sc SD mS ir wX bm ta --count fu pc ls Ra c mF --help mC --report push fb sl --since Ct ia wR rm f lv sp mv clear -r l1 pF ue wC rename t user wS cd Su --information repo --dry-run ix --version Ca Cl b iu -t bL Ce savepd Rm Co lr Rx"
      COMPREPLY=($(compgen -W "$COMP_WORD" -- ${COMP_WORDS[${COMP_CWORD}]}))
  fi
}

complete -F _pigit_completion pigit
