#!/usr/env bash

_pigit_completion(){
  if [[ "${COMP_CWORD}" == "1" ]];then
      COMP_WORD="pt Ct Rm cF -h open clear wx --create-config fb wR lv --dry-run --help Ce wC ws --types iD fC mS f --version --information -p RS pa email fetch push m bd pc t wr Sd -v fc --complete fm Ru SD --reverse s ls add c R ir pA iX fu Si wX bc --issue b mv --report ld rename cm --config id Rs wD savepd mt Su cA -t --print cR mC sl CT lr --show-part-command sd wM sD iA cd pF --shell ca Cl bl co iu repo ia --path Rl tx wm l Rp cr pp bm pf cf ma ll --commit Ra p ue cs bS -s cO Co mF --show-commands wS wc cmd --simple user sp -r wd -i bL Ca l1 rm --create-ignore bM bs --count -f lc Rx iR Sc pull ta CO fr ix -c"
      COMPREPLY=($(compgen -W "$COMP_WORD" -- ${COMP_WORDS[${COMP_CWORD}]}))
  fi
}

complete -F _pigit_completion pigit
